language: node_js
node_js:
- '0.10'
env:
  global:
  - PATH: node_modules/.bin/:$PATH
  - REPO_SLUG: scrat-team/scrat-team.github.io
  - secure: BhZRYbcOBhSv00Z2k6CgvOnceq+tHKT0TMDa+/bnijQTxqUa0qeqfD7ZiXyfWK3ciqDJ+NZ9PQGNHoCNrGDnrUQjlC27rFrYpnxqeBKcoH/o5JXULs9QxVgyNJW9xczUGl3eT5FmX4M5Y5uyQvYSqP3Z3faNpilGaLc5JWGWzw0=
install:
- npm install scrat
- scrat -v
script:
- scrat release -loumd output
after_success:
- sh .build.sh
cache:
  directories:
  - node_modules
branches:
  only:
  - master
